#!/usr/bin/env python3
# STD
from os import chdir,listdir,makedirs,remove
from os.path import expanduser,isdir
from shutil import copyfile
from subprocess import run
from sys import argv
# External
import youtube_dl

outdir = expanduser("~/.cache/yt_dw")
destdir = expanduser("~/Videos/Youtube")
for d in [outdir,destdir]:
    if not isdir(d):
        makedirs(d)

def main():
    if len(argv) == 2:
        start(argv[1])
    else:
        print("Exactly one argument needed")
    return

def start(u):
    chdir(outdir)
    notify("Started downloading: "+u)
    r = dl(u)
    if r == 0:
        m = "Finished downloading: "+u
    else:
        m = "Failed downloading: "+u
    notify(m)
    return

def notify(m):
    p = run(["notify-send", m])
    return p.returncode

def dl(u):
    opts = {
        'format': "best[height<=720]",
        'outtmpl': "%(id)s [%(uploader)s] %(title)s.%(ext)s"
    }
    try:
        with youtube_dl.YoutubeDL(opts) as y:
            y.download([u])
        for f in listdir("."):
            if not f.endswith(".part"):
                move(f)
        r = 0
    except Exception:
        r = 1
    return r

def move(f):
    # Get latest index
    n = len( listdir(destdir) )
    t = f[ f.find(" ")+1: ]
    s = "{}/{:0>3} {}".format(destdir,n,t)
    print(s)
    copyfile(f,s)
    remove(f)

if __name__ == "__main__":
    main()
